set(FILES
content/pencil/aboutDialog.js
content/pencil/settingDialog.xul
content/pencil/exporter/webPageExporter.js
content/pencil/exporter/otherExporters.js
content/pencil/exporter/odtExporter.js
content/pencil/exporter/baseExporter.js
content/pencil/exporter/baseRasterizedExporter.js
content/pencil/exporter/ooConversionExporter.js
content/pencil/privateShapeDialog.xul
content/pencil/clipartBrowser.xul
content/pencil/privateShapeDialog.js
content/pencil/pageDetailDialog.xul
content/pencil/definition/geometry.js
content/pencil/definition/shapeDefCollectionParser.js
content/pencil/definition/collectionManager.js
content/pencil/definition/exportTemplateManager.js
content/pencil/definition/exportTemplate.js
content/pencil/definition/shapeDef.js
content/pencil/definition/shapeDefCollection.js
content/pencil/editor/propertyPageEditor.js
content/pencil/editor/sharedGeometryEditor.js
content/pencil/editor/onScreenTextEditor.js
content/pencil/editor/onMenuEditor.js
content/pencil/editor/handleEditor.js
content/pencil/editor/onMenuTypeEditors.js
content/pencil/editor/sharedFillColorEditor.js
content/pencil/editor/geometryEditor.js
content/pencil/editor/geometryEditor.config.xml
content/pencil/editor/onScreenTextEditor-RichTextSupport.js
content/pencil/editor/handleEditor.config.xml
content/pencil/editor/sharedFontEditor.js
content/pencil/editor/onScreenTextEditor.config.xml
content/pencil/firefoxOverlay.js
content/pencil/pageNoteDialog.xul
content/pencil/textToolOverlay.xul
content/pencil/progressDialog.xul
content/pencil/clipartBrowser/clipartBrowser.js
content/pencil/clipartBrowser/webUtil.js
content/pencil/clipartBrowser/googleImageSearch.js
content/pencil/clipartBrowser/searchService.js
content/pencil/clipartBrowser/newOpenClipartSearch.js
content/pencil/clipartBrowser/searchEngine.js
content/pencil/clipartBrowser/openClipartSearch.js
content/pencil/behavior/commonFunctions.js
content/pencil/behavior/commonBehaviors.js
content/pencil/document/document.js
content/pencil/document/xmlDocumentPersister.js
content/pencil/document/persistentHooks.js
content/pencil/privateCollectionDialog.xul
content/pencil/propertyDialog.js
content/pencil/colorToolOverlay.xul
content/pencil/propertyDialog.xul
content/pencil/propertyType/enum.js
content/pencil/propertyType/dimension.js
content/pencil/propertyType/point.js
content/pencil/propertyType/snappingData.js
content/pencil/propertyType/css.js
content/pencil/propertyType/bound.js
content/pencil/propertyType/imageData.js
content/pencil/propertyType/handle.js
content/pencil/propertyType/alignment.js
content/pencil/propertyType/shadowStyle.js
content/pencil/propertyType/color.js
content/pencil/propertyType/strokeStyle.js
content/pencil/propertyType/bool.js
content/pencil/propertyType/plainText.js
content/pencil/propertyType/font.js
content/pencil/propertyType/richTextArray.js
content/pencil/propertyType/richText.js
content/pencil/canvasHelper/canvasCareTaker.js
content/pencil/canvasHelper/canvasImpl.js
content/pencil/canvasHelper/canvasMemento.js
content/pencil/canvasHelper/snappingHelper.js
content/pencil/templateManagementDialog.js
content/pencil/privateCollectionDialog.js
content/pencil/templateManagementDialog.xul
content/pencil/blank.html
content/pencil/xferHelper/pngImageXferHelper.js
content/pencil/xferHelper/svgXferHelper.js
content/pencil/xferHelper/targetSetXferHelper.js
content/pencil/xferHelper/shapeXferHelper.js
content/pencil/xferHelper/dragObservers.js
content/pencil/xferHelper/rRichTextXferHelper.js
content/pencil/stencilGenerator.js
content/pencil/pageDetailDialog.js
content/pencil/pageNoteDialog.js
content/pencil/privateCollectionWizard.xul
content/pencil/exportWizard.js
content/pencil/target/null.js
content/pencil/target/shape.js
content/pencil/target/targetSet.js
content/pencil/target/group.js
content/pencil/privateCollectionWizard.js
content/pencil/firefoxOverlay.xul
content/pencil/editor-blank.html
content/pencil/bindings/colorPickerButton.xbl
content/pencil/bindings/colorEditor.xbl
content/pencil/bindings/editorWrapper.css
content/pencil/bindings/shadowStyleEditor.css
content/pencil/bindings/enumEditor.xbl
content/pencil/bindings/searchBar.xbl
content/pencil/bindings/enumEditor.css
content/pencil/bindings/fontEditor.css
content/pencil/bindings/privateCollectionPane.css
content/pencil/bindings/collectionPane.xbl
content/pencil/bindings/commonEditors.css
content/pencil/bindings/editorWrapper.xbl
content/pencil/bindings/searchBar.css
content/pencil/bindings/shadowStyleEditor.xbl
content/pencil/bindings/plainTextEditor.xbl
content/pencil/bindings/fontEditor.xbl
content/pencil/bindings/pCanvas.xbl
content/pencil/bindings/ColorEditor-Preview-Bg.png
content/pencil/bindings/strokeEditor.xbl
content/pencil/bindings/strokeEditor.css
content/pencil/bindings/alignEditor.xbl
content/pencil/bindings/privateCollectionPane.xbl
content/pencil/bindings/alignEditor.css
content/pencil/bindings/clipartBrowserPane.css
content/pencil/bindings/colorPickers.xbl
content/pencil/bindings/colorPickers.css
content/pencil/bindings/color-wheel-90.png
content/pencil/bindings/colorPickerButton.css
content/pencil/bindings/clipartBrowserPane.xbl
content/pencil/bindings/plainTextEditor.css
content/pencil/bindings/colorEditor.css
content/pencil/bindings/collectionPane.css
content/pencil/bindings/color-wheel-70.png
content/pencil/stencilGenerator.xul
content/pencil/mainWindow.js
content/pencil/progressDialog.js
content/pencil/settingDialog.js
content/pencil/license.txt
content/pencil/privateCollection/privateCollection.js
content/pencil/privateCollection/privateCollectionManager.js
content/pencil/privateCollection/privateShapeDef.js
content/pencil/privateCollection/privateShapeDefParser.js
content/pencil/messageDialog.xul
content/pencil/exportWizard.xul
content/pencil/messageDialog.js
content/pencil/common/collectionSettingEditor.js
content/pencil/common/abstractSymbol.js
content/pencil/common/util.js
content/pencil/common/io.js
content/pencil/common/lorem.js
content/pencil/common/nsTransferable.js
content/pencil/common/base64.js
content/pencil/common/nsDragAndDrop.js
content/pencil/common/controller.js
content/pencil/common/tree.js
content/pencil/common/stencilEditor.js
content/pencil/common/svgRasterizer.js
content/pencil/common/sax.js
content/pencil/common/config.js
content/pencil/common/externalEditorSupports.js
content/pencil/common/dockingManager.js
content/pencil/common/colorDroppers.js
content/pencil/common/pencilNamespaces.js
content/pencil/common/typeEditorRegistry.js
content/pencil/common/richTextDialog.js
content/pencil/stencil/SketchyGUI/Icons/bread.png
content/pencil/stencil/SketchyGUI/Icons/selected-checkbox.png
content/pencil/stencil/SketchyGUI/Icons/image.png
content/pencil/stencil/SketchyGUI/Icons/box.png
content/pencil/stencil/SketchyGUI/Icons/progressbar.png
content/pencil/stencil/SketchyGUI/Icons/button.png
content/pencil/stencil/SketchyGUI/Icons/selected-radio.png
content/pencil/stencil/SketchyGUI/Icons/password-field.png
content/pencil/stencil/SketchyGUI/Icons/tab.png
content/pencil/stencil/SketchyGUI/Icons/checkbox.png
content/pencil/stencil/SketchyGUI/Icons/circle-triangle.png
content/pencil/stencil/SketchyGUI/Icons/radio.png
content/pencil/stencil/SketchyGUI/Icons/checked-checkbox.png
content/pencil/stencil/SketchyGUI/Icons/scale.png
content/pencil/stencil/SketchyGUI/Icons/html.png
content/pencil/stencil/SketchyGUI/Icons/line.png
content/pencil/stencil/SketchyGUI/Icons/combobox.png
content/pencil/stencil/SketchyGUI/Icons/messagebox.png
content/pencil/stencil/SketchyGUI/Icons/label.png
content/pencil/stencil/SketchyGUI/Icons/winframe.png
content/pencil/stencil/SketchyGUI/Icons/listbox.png
content/pencil/stencil/SketchyGUI/Icons/table.png
content/pencil/stencil/SketchyGUI/Icons/scrollbar.png
content/pencil/stencil/SketchyGUI/Icons/textfield.png
content/pencil/stencil/SketchyGUI/Icons/link.png
content/pencil/stencil/SketchyGUI/Icons/sketchy-triangle.png
content/pencil/stencil/SketchyGUI/Definition.xml
content/pencil/stencil/BasicWebElements/Icons/bread.png
content/pencil/stencil/BasicWebElements/Icons/h4.png
content/pencil/stencil/BasicWebElements/Icons/pane.png
content/pencil/stencil/BasicWebElements/Icons/h3.png
content/pencil/stencil/BasicWebElements/Icons/h5.png
content/pencil/stencil/BasicWebElements/Icons/html.png
content/pencil/stencil/BasicWebElements/Icons/h2.png
content/pencil/stencil/BasicWebElements/Icons/table.png
content/pencil/stencil/BasicWebElements/Icons/h1.png
content/pencil/stencil/BasicWebElements/Icons/link.png
content/pencil/stencil/BasicWebElements/Icons/hr.png
content/pencil/stencil/BasicWebElements/Definition.xml
content/pencil/stencil/Annotation/Icons/balloon.png
content/pencil/stencil/Annotation/Icons/hollowbox.png
content/pencil/stencil/Annotation/Icons/bullet.png
content/pencil/stencil/Annotation/Icons/arrow.png
content/pencil/stencil/Annotation/Icons/icons.ep
content/pencil/stencil/Annotation/Definition.xml
content/pencil/stencil/Common/Icons/oval.png
content/pencil/stencil/Common/Icons/free-line.png
content/pencil/stencil/Common/Icons/rectangle-grad.png
content/pencil/stencil/Common/Icons/triangle.png
content/pencil/stencil/Common/Icons/balloon.png
content/pencil/stencil/Common/Icons/rich-text.png
content/pencil/stencil/Common/Icons/hline.png
content/pencil/stencil/Common/Icons/bullet.png
content/pencil/stencil/Common/Icons/bitmap.png
content/pencil/stencil/Common/Icons/rectangle.png
content/pencil/stencil/Common/Icons/plain-text.png
content/pencil/stencil/Common/Definition.xml
icons/default/main-window.png
icons/default/main-window.16.png
icons/default/main-window.48.png
icons/default/main-window.ico
icons/default/main-window.32.png
icons/default/main-window.icns
platform/WINNT/chrome.manifest
chrome/icons/default/main-window.png
chrome/icons/default/main-window.16.png
chrome/icons/default/main-window.48.png
chrome/icons/default/main-window.ico
chrome/icons/default/main-window.32.png
skin/classic/settingDialog.css
skin/classic/images/align-center-center.png
skin/classic/images/pan_off.png
skin/classic/images/mono-24/text-color.png
skin/classic/images/mono-24/zoom.png
skin/classic/images/mono-24/border-color.png
skin/classic/images/mono-24/fill-color.png
skin/classic/images/mono-24/save.png
skin/classic/images/search-glass-rtl.png
skin/classic/images/dialog-warning.png
skin/classic/images/paypal.png
skin/classic/images/align-left-center.png
skin/classic/images/textarea-sizegrip.png
skin/classic/images/align-left-bottom.png
skin/classic/images/align-right-center.png
skin/classic/images/tab.png
skin/classic/images/seperator.png
skin/classic/images/pandown.cur
skin/classic/images/collection-filter.png
skin/classic/images/twisty.png
skin/classic/images/format-painter-16.png
skin/classic/images/format-painter.png
skin/classic/images/Editor/font-box-background.png
skin/classic/images/Editor/text_bold.png
skin/classic/images/Editor/image.png
skin/classic/images/Editor/text_full.png
skin/classic/images/Editor/delete-2416.png
skin/classic/images/Editor/text_super.png
skin/classic/images/Editor/indent.png
skin/classic/images/Editor/text_right.png
skin/classic/images/Editor/horz-rule.png
skin/classic/images/Editor/text_center.png
skin/classic/images/Editor/decrease_text_size.png
skin/classic/images/Editor/insert-image.png
skin/classic/images/Editor/emails.png
skin/classic/images/Editor/numbered-list.png
skin/classic/images/Editor/anchor-16.png
skin/classic/images/Editor/text_size.png
skin/classic/images/Editor/text_strike.png
skin/classic/images/Editor/text_font.png
skin/classic/images/Editor/filesave.png
skin/classic/images/Editor/menu-bg.png
skin/classic/images/Editor/filenew.png
skin/classic/images/Editor/text_sub.png
skin/classic/images/Editor/bulleted-list.png
skin/classic/images/Editor/blank-note-16.png
skin/classic/images/Editor/text_italic.png
skin/classic/images/Editor/blank-note-2416.png
skin/classic/images/Editor/edittrash.png
skin/classic/images/Editor/text_left.png
skin/classic/images/Editor/size-box-background.png
skin/classic/images/Editor/save-2416.png
skin/classic/images/Editor/outdent.png
skin/classic/images/Editor/text_color.png
skin/classic/images/Editor/delete-16.png
skin/classic/images/Editor/folder-2416.png
skin/classic/images/Editor/blank-note-32.png
skin/classic/images/Editor/link.png
skin/classic/images/Editor/text_under.png
skin/classic/images/Editor/folder-16.png
skin/classic/images/Editor/increase_text_size.png
skin/classic/images/pane-selector-macosx-bg.png
skin/classic/images/pd.png
skin/classic/images/pane-external-editor.png
skin/classic/images/pencil.ico
skin/classic/images/search-glass.png
skin/classic/images/dialog-information.png
skin/classic/images/size-grip.png
skin/classic/images/dialog-error.png
skin/classic/images/throbber.gif
skin/classic/images/moblin/format-justify-right.png
skin/classic/images/moblin/document-new.png
skin/classic/images/moblin/format-text-bold.png
skin/classic/images/moblin/object-rotate-right.png
skin/classic/images/moblin/edit-cut.png
skin/classic/images/moblin/edit-select-all.png
skin/classic/images/moblin/edit-redo.png
skin/classic/images/moblin/format-justify-fill.png
skin/classic/images/moblin/format-justify-center.png
skin/classic/images/moblin/edit-paste.png
skin/classic/images/moblin/edit-undo.png
skin/classic/images/moblin/zoom-in.png
skin/classic/images/moblin/document-open.png
skin/classic/images/moblin/format-justify-left.png
skin/classic/images/moblin/zoom-original.png
skin/classic/images/moblin/zoom-out.png
skin/classic/images/moblin/weather-overcast.png
skin/classic/images/moblin/format-indent-less.png
skin/classic/images/moblin/edit-delete.png
skin/classic/images/moblin/format-text-underline.png
skin/classic/images/moblin/format-indent-more.png
skin/classic/images/moblin/tuxpaint.png
skin/classic/images/moblin/gnote.png
skin/classic/images/moblin/document-save.png
skin/classic/images/moblin/system-config-printer.png
skin/classic/images/moblin/format-bullets.png
skin/classic/images/moblin/edit-copy.png
skin/classic/images/moblin/format-text-italic.png
skin/classic/images/align-center-top.png
skin/classic/images/MozIcons/stock/stock_insert_url.png
skin/classic/images/MozIcons/stock/zoom-original-menu.png
skin/classic/images/MozIcons/stock/document-save-as-menu.png
skin/classic/images/MozIcons/stock/format_text_italic.png
skin/classic/images/MozIcons/stock/add-menu.png
skin/classic/images/MozIcons/stock/format-indent-less-menu.png
skin/classic/images/MozIcons/stock/stock_pin.png
skin/classic/images/MozIcons/stock/stock_draw_selection.png
skin/classic/images/MozIcons/stock/edit_copy.png
skin/classic/images/MozIcons/stock/edit_cut.png
skin/classic/images/MozIcons/stock/format_justify_center.png
skin/classic/images/MozIcons/stock/stock_stroke_color.png
skin/classic/images/MozIcons/stock/stock_text_quickedit.png
skin/classic/images/MozIcons/stock/document-new.png
skin/classic/images/MozIcons/stock/document-save-as.png
skin/classic/images/MozIcons/stock/format-text-strikethrough-menu.png
skin/classic/images/MozIcons/stock/stock_graphics_align_middle.png
skin/classic/images/MozIcons/stock/stock_save_pdf.png
skin/classic/images/MozIcons/stock/edit_paste.png
skin/classic/images/MozIcons/stock/stock_insert_endnote.png
skin/classic/images/MozIcons/stock/stock_cell_align_bottom.png
skin/classic/images/MozIcons/stock/insert_link.png
skin/classic/images/MozIcons/stock/insert-link-menu.png
skin/classic/images/MozIcons/stock/stock_zoom_1.png
skin/classic/images/MozIcons/stock/document_export.png
skin/classic/images/MozIcons/stock/format_justify_left.png
skin/classic/images/MozIcons/stock/document-open-menu.png
skin/classic/images/MozIcons/stock/stock_font_size.png
skin/classic/images/MozIcons/stock/edit_delete.png
skin/classic/images/MozIcons/stock/stock_text_color_background-menu.png
skin/classic/images/MozIcons/stock/stock_zoom_out.png
skin/classic/images/MozIcons/stock/stock_graphics_align_center.png
skin/classic/images/MozIcons/stock/stock_graphics_align_right.png
skin/classic/images/MozIcons/stock/stock_autofilter.png
skin/classic/images/MozIcons/stock/remove-menu.png
skin/classic/images/MozIcons/stock/stock_zoom_in.png
skin/classic/images/MozIcons/stock/format_text_bold.png
skin/classic/images/MozIcons/stock/next-menu.png
skin/classic/images/MozIcons/stock/stock_snap_object_points.png
skin/classic/images/MozIcons/stock/zoom-out-menu.png
skin/classic/images/MozIcons/stock/stock_reverse_order.png
skin/classic/images/MozIcons/stock/stock_snap_grid.png
skin/classic/images/MozIcons/stock/toolbar/stock_graphics-align-left.png
skin/classic/images/MozIcons/stock/toolbar/add.png
skin/classic/images/MozIcons/stock/toolbar/help.png
skin/classic/images/MozIcons/stock/toolbar/format-justify-right.png
skin/classic/images/MozIcons/stock/toolbar/stock_stroke_color.png
skin/classic/images/MozIcons/stock/toolbar/document-new.png
skin/classic/images/MozIcons/stock/toolbar/document-save-as.png
skin/classic/images/MozIcons/stock/toolbar/revert.png
skin/classic/images/MozIcons/stock/toolbar/stock_graphics-align-middle.png
skin/classic/images/MozIcons/stock/toolbar/format-text-strikethrough.png
skin/classic/images/MozIcons/stock/toolbar/format-text-bold.png
skin/classic/images/MozIcons/stock/toolbar/stock_to-bottom.png
skin/classic/images/MozIcons/stock/toolbar/object-rotate-right.png
skin/classic/images/MozIcons/stock/toolbar/gtk-fullscreen.png
skin/classic/images/MozIcons/stock/toolbar/stock_bring-backward.png
skin/classic/images/MozIcons/stock/toolbar/process-stop.png
skin/classic/images/MozIcons/stock/toolbar/document-export.png
skin/classic/images/MozIcons/stock/toolbar/edit-cut.png
skin/classic/images/MozIcons/stock/toolbar/edit-select-all.png
skin/classic/images/MozIcons/stock/toolbar/gtk-help.png
skin/classic/images/MozIcons/stock/toolbar/stock_object-behind.png
skin/classic/images/MozIcons/stock/toolbar/edit-redo.png
skin/classic/images/MozIcons/stock/toolbar/document-print.png
skin/classic/images/MozIcons/stock/toolbar/forward.png
skin/classic/images/MozIcons/stock/toolbar/back.png
skin/classic/images/MozIcons/stock/toolbar/document-open-recent.png
skin/classic/images/MozIcons/stock/toolbar/format-justify-fill.png
skin/classic/images/MozIcons/stock/toolbar/insert-text.png
skin/classic/images/MozIcons/stock/toolbar/undo.png
skin/classic/images/MozIcons/stock/toolbar/format-justify-center.png
skin/classic/images/MozIcons/stock/toolbar/document-revert.png
skin/classic/images/MozIcons/stock/toolbar/insert-image.png
skin/classic/images/MozIcons/stock/toolbar/edit-paste.png
skin/classic/images/MozIcons/stock/toolbar/edit-undo.png
skin/classic/images/MozIcons/stock/toolbar/next.png
skin/classic/images/MozIcons/stock/toolbar/edit-find.png
skin/classic/images/MozIcons/stock/toolbar/zoom-in.png
skin/classic/images/MozIcons/stock/toolbar/document-open.png
skin/classic/images/MozIcons/stock/toolbar/stock_list_bullet.png
skin/classic/images/MozIcons/stock/toolbar/format-justify-left.png
skin/classic/images/MozIcons/stock/toolbar/zoom-original.png
skin/classic/images/MozIcons/stock/toolbar/stock_to-top.png
skin/classic/images/MozIcons/stock/toolbar/make-same-horizontal-space.png
skin/classic/images/MozIcons/stock/toolbar/stock_graphics-align-bottom.png
skin/classic/images/MozIcons/stock/toolbar/stock_3d-color-picker.png
skin/classic/images/MozIcons/stock/toolbar/zoom-out.png
skin/classic/images/MozIcons/stock/toolbar/remove.png
skin/classic/images/MozIcons/stock/toolbar/zoom-best-fit.png
skin/classic/images/MozIcons/stock/toolbar/object-rotate-left.png
skin/classic/images/MozIcons/stock/toolbar/gtk-cancel.png
skin/classic/images/MozIcons/stock/toolbar/format-indent-less.png
skin/classic/images/MozIcons/stock/toolbar/stock_list_enum.png
skin/classic/images/MozIcons/stock/toolbar/object-flip-vertical.png
skin/classic/images/MozIcons/stock/toolbar/insert-link.png
skin/classic/images/MozIcons/stock/toolbar/help-contents.png
skin/classic/images/MozIcons/stock/toolbar/edit-delete.png
skin/classic/images/MozIcons/stock/toolbar/document-properties.png
skin/classic/images/MozIcons/stock/toolbar/exit.png
skin/classic/images/MozIcons/stock/toolbar/make-same-vertical-space.png
skin/classic/images/MozIcons/stock/toolbar/object-flip-horizontal.png
skin/classic/images/MozIcons/stock/toolbar/format-text-direction-rtl.png
skin/classic/images/MozIcons/stock/toolbar/gtk-about.png
skin/classic/images/MozIcons/stock/toolbar/stock_bucketfill.png
skin/classic/images/MozIcons/stock/toolbar/format-text-direction-ltr.png
skin/classic/images/MozIcons/stock/toolbar/gtk-edit.png
skin/classic/images/MozIcons/stock/toolbar/stock_object-infront.png
skin/classic/images/MozIcons/stock/toolbar/stock_text_color_background.png
skin/classic/images/MozIcons/stock/toolbar/format-text-underline.png
skin/classic/images/MozIcons/stock/toolbar/window-new.png
skin/classic/images/MozIcons/stock/toolbar/format-indent-more.png
skin/classic/images/MozIcons/stock/toolbar/stock_graphics-align-right.png
skin/classic/images/MozIcons/stock/toolbar/previous.png
skin/classic/images/MozIcons/stock/toolbar/stock_bring-forward.png
skin/classic/images/MozIcons/stock/toolbar/edit-clear.png
skin/classic/images/MozIcons/stock/toolbar/stock_graphics-align-center.png
skin/classic/images/MozIcons/stock/toolbar/stock_text_color_foreground.png
skin/classic/images/MozIcons/stock/toolbar/gnome-run.png
skin/classic/images/MozIcons/stock/toolbar/gtk-execute.png
skin/classic/images/MozIcons/stock/toolbar/redhat-home.png
skin/classic/images/MozIcons/stock/toolbar/document-save.png
skin/classic/images/MozIcons/stock/toolbar/help-about.png
skin/classic/images/MozIcons/stock/toolbar/redo.png
skin/classic/images/MozIcons/stock/toolbar/edit-copy.png
skin/classic/images/MozIcons/stock/toolbar/gtk-close.png
skin/classic/images/MozIcons/stock/toolbar/insert-object.png
skin/classic/images/MozIcons/stock/toolbar/format-text-italic.png
skin/classic/images/MozIcons/stock/toolbar/stock_graphics-align-top.png
skin/classic/images/MozIcons/stock/toolbar/tab-new.png
skin/classic/images/MozIcons/stock/toolbar/stock_text_color_hilight.png
skin/classic/images/MozIcons/stock/toolbar/edit-find-replace.png
skin/classic/images/MozIcons/stock/toolbar/help-faq.png
skin/classic/images/MozIcons/stock/toolbar/centrejust.png
skin/classic/images/MozIcons/stock/insert_image.png
skin/classic/images/MozIcons/stock/edit-cut-menu.png
skin/classic/images/MozIcons/stock/stock_font.png
skin/classic/images/MozIcons/stock/edit-select-all-menu.png
skin/classic/images/MozIcons/stock/edit-redo-menu.png
skin/classic/images/MozIcons/stock/stock_draw_text_frame.png
skin/classic/images/MozIcons/stock/stock_hyperlink_toolbar.png
skin/classic/images/MozIcons/stock/gtk_edit.png
skin/classic/images/MozIcons/stock/menu/rightjust.png
skin/classic/images/MozIcons/stock/menu/gtk-jump-to-rtl.png
skin/classic/images/MozIcons/stock/menu/gtk-go-up.png
skin/classic/images/MozIcons/stock/menu/stock_text_indent.png
skin/classic/images/MozIcons/stock/menu/filesaveas.png
skin/classic/images/MozIcons/stock/menu/gtk-print-preview.png
skin/classic/images/MozIcons/stock/menu/gtk-bold.png
skin/classic/images/MozIcons/stock/menu/stock_spam.png
skin/classic/images/MozIcons/stock/menu/gtk-redo-ltr.png
skin/classic/images/MozIcons/stock/menu/viewmag+.png
skin/classic/images/MozIcons/stock/menu/text_bold.png
skin/classic/images/MozIcons/stock/menu/gtk-justify-fill.png
skin/classic/images/MozIcons/stock/menu/window_fullscreen.png
skin/classic/images/MozIcons/stock/menu/gtk-save-as.png
skin/classic/images/MozIcons/stock/menu/gnome-stock-text-unindent.png
skin/classic/images/MozIcons/stock/menu/add.png
skin/classic/images/MozIcons/stock/menu/media-seek-backward.png
skin/classic/images/MozIcons/stock/menu/gtk-goto-last-rtl.png
skin/classic/images/MozIcons/stock/menu/window_new.png
skin/classic/images/MozIcons/stock/menu/system-shutdown.png
skin/classic/images/MozIcons/stock/menu/help.png
skin/classic/images/MozIcons/stock/menu/go-jump.png
skin/classic/images/MozIcons/stock/menu/stock_stop.png
skin/classic/images/MozIcons/stock/menu/format-justify-right.png
skin/classic/images/MozIcons/stock/menu/gtk-revert-to-saved-rtl.png
skin/classic/images/MozIcons/stock/menu/gtk-sort-ascending.png
skin/classic/images/MozIcons/stock/menu/stock_media-play.png
skin/classic/images/MozIcons/stock/menu/system-lock-screen.png
skin/classic/images/MozIcons/stock/menu/document-new.png
skin/classic/images/MozIcons/stock/menu/gtk-select-all.png
skin/classic/images/MozIcons/stock/menu/stock_media-rec.png
skin/classic/images/MozIcons/stock/menu/stock_text_center.png
skin/classic/images/MozIcons/stock/menu/viewmagfit.png
skin/classic/images/MozIcons/stock/menu/document-save-as.png
skin/classic/images/MozIcons/stock/menu/mail-mark-notjunk.png
skin/classic/images/MozIcons/stock/menu/player_record.png
skin/classic/images/MozIcons/stock/menu/revert.png
skin/classic/images/MozIcons/stock/menu/stock_new-dir.png
skin/classic/images/MozIcons/stock/menu/gtk-go-forward-rtl.png
skin/classic/images/MozIcons/stock/menu/format-text-strikethrough.png
skin/classic/images/MozIcons/stock/menu/address-book-new.png
skin/classic/images/MozIcons/stock/menu/stock_save-as.png
skin/classic/images/MozIcons/stock/menu/gtk-unindent-ltr.png
skin/classic/images/MozIcons/stock/menu/gtk-cut.png
skin/classic/images/MozIcons/stock/menu/format-text-bold.png
skin/classic/images/MozIcons/stock/menu/kfind.png
skin/classic/images/MozIcons/stock/menu/object-rotate-right.png
skin/classic/images/MozIcons/stock/menu/gtk-fullscreen.png
skin/classic/images/MozIcons/stock/menu/kfm_home.png
skin/classic/images/MozIcons/stock/menu/stock_media-stop.png
skin/classic/images/MozIcons/stock/menu/process-stop.png
skin/classic/images/MozIcons/stock/menu/gtk-goto-top.png
skin/classic/images/MozIcons/stock/menu/media-eject.png
skin/classic/images/MozIcons/stock/menu/system-run.png
skin/classic/images/MozIcons/stock/menu/go-first.png
skin/classic/images/MozIcons/stock/menu/gtk-justify-left.png
skin/classic/images/MozIcons/stock/menu/gtk-media-rewind-ltr.png
skin/classic/images/MozIcons/stock/menu/appointment-new.png
skin/classic/images/MozIcons/stock/menu/media-skip-forward.png
skin/classic/images/MozIcons/stock/menu/mail_spam.png
skin/classic/images/MozIcons/stock/menu/go-previous.png
skin/classic/images/MozIcons/stock/menu/edit-cut.png
skin/classic/images/MozIcons/stock/menu/edit-select-all.png
skin/classic/images/MozIcons/stock/menu/gnome-stock-mail-snd.png
skin/classic/images/MozIcons/stock/menu/gtk-help.png
skin/classic/images/MozIcons/stock/menu/gtk-media-forward-ltr.png
skin/classic/images/MozIcons/stock/menu/gnome-lockscreen.png
skin/classic/images/MozIcons/stock/menu/appointment.png
skin/classic/images/MozIcons/stock/menu/stock_new-address-book.png
skin/classic/images/MozIcons/stock/menu/stock_leave-fullscreen.png
skin/classic/images/MozIcons/stock/menu/filequickprint.png
skin/classic/images/MozIcons/stock/menu/gnome-stock-mail-fwd.png
skin/classic/images/MozIcons/stock/menu/editcut.png
skin/classic/images/MozIcons/stock/menu/stock_add-bookmark.png
skin/classic/images/MozIcons/stock/menu/gtk-media-record.png
skin/classic/images/MozIcons/stock/menu/stock_text-strikethrough.png
skin/classic/images/MozIcons/stock/menu/gtk-media-next-rtl.png
skin/classic/images/MozIcons/stock/menu/edit-redo.png
skin/classic/images/MozIcons/stock/menu/media-record.png
skin/classic/images/MozIcons/stock/menu/gnome-searchtool.png
skin/classic/images/MozIcons/stock/menu/stock_print-preview.png
skin/classic/images/MozIcons/stock/menu/document-print.png
skin/classic/images/MozIcons/stock/menu/forward.png
skin/classic/images/MozIcons/stock/menu/media-playback-start.png
skin/classic/images/MozIcons/stock/menu/back.png
skin/classic/images/MozIcons/stock/menu/player_eject.png
skin/classic/images/MozIcons/stock/menu/application-exit.png
skin/classic/images/MozIcons/stock/menu/view-sort-descending.png
skin/classic/images/MozIcons/stock/menu/reload_page.png
skin/classic/images/MozIcons/stock/menu/stock_zoom-page.png
skin/classic/images/MozIcons/stock/menu/stock_right.png
skin/classic/images/MozIcons/stock/menu/stock_media-pause.png
skin/classic/images/MozIcons/stock/menu/gtk-indent-ltr.png
skin/classic/images/MozIcons/stock/menu/view-sort-ascending.png
skin/classic/images/MozIcons/stock/menu/mail_new.png
skin/classic/images/MozIcons/stock/menu/xfce-system-exit.png
skin/classic/images/MozIcons/stock/menu/mail_reply.png
skin/classic/images/MozIcons/stock/menu/go-down.png
skin/classic/images/MozIcons/stock/menu/document-open-recent.png
skin/classic/images/MozIcons/stock/menu/stock_left.png
skin/classic/images/MozIcons/stock/menu/stock_text_justify.png
skin/classic/images/MozIcons/stock/menu/stock_refresh.png
skin/classic/images/MozIcons/stock/menu/gtk-justify-center.png
skin/classic/images/MozIcons/stock/menu/go-up.png
skin/classic/images/MozIcons/stock/menu/window-close.png
skin/classic/images/MozIcons/stock/menu/list-remove.png
skin/classic/images/MozIcons/stock/menu/format-justify-fill.png
skin/classic/images/MozIcons/stock/menu/insert-text.png
skin/classic/images/MozIcons/stock/menu/undo.png
skin/classic/images/MozIcons/stock/menu/stock_file-properites.png
skin/classic/images/MozIcons/stock/menu/format-justify-center.png
skin/classic/images/MozIcons/stock/menu/gtk-remove.png
skin/classic/images/MozIcons/stock/menu/stock_search-and-replace.png
skin/classic/images/MozIcons/stock/menu/gtk-sort-descending.png
skin/classic/images/MozIcons/stock/menu/stock_home.png
skin/classic/images/MozIcons/stock/menu/editcopy.png
skin/classic/images/MozIcons/stock/menu/stock_copy.png
skin/classic/images/MozIcons/stock/menu/mail-mark-read.png
skin/classic/images/MozIcons/stock/menu/gtk-indent-rtl.png
skin/classic/images/MozIcons/stock/menu/stock_down.png
skin/classic/images/MozIcons/stock/menu/document-revert.png
skin/classic/images/MozIcons/stock/menu/gtk-media-next-ltr.png
skin/classic/images/MozIcons/stock/menu/gtk-spell-check.png
skin/classic/images/MozIcons/stock/menu/folder-new.png
skin/classic/images/MozIcons/stock/menu/player_pause.png
skin/classic/images/MozIcons/stock/menu/player_start.png
skin/classic/images/MozIcons/stock/menu/editpaste.png
skin/classic/images/MozIcons/stock/menu/gtk-media-stop.png
skin/classic/images/MozIcons/stock/menu/insert-image.png
skin/classic/images/MozIcons/stock/menu/gtk-goto-first-ltr.png
skin/classic/images/MozIcons/stock/menu/edit-paste.png
skin/classic/images/MozIcons/stock/menu/stock_close.png
skin/classic/images/MozIcons/stock/menu/reload_all_tabs.png
skin/classic/images/MozIcons/stock/menu/player_play.png
skin/classic/images/MozIcons/stock/menu/mail_send.png
skin/classic/images/MozIcons/stock/menu/edit-undo.png
skin/classic/images/MozIcons/stock/menu/next.png
skin/classic/images/MozIcons/stock/menu/edit-find.png
skin/classic/images/MozIcons/stock/menu/gtk-home.png
skin/classic/images/MozIcons/stock/menu/gtk-save.png
skin/classic/images/MozIcons/stock/menu/zoom-in.png
skin/classic/images/MozIcons/stock/menu/document-open.png
skin/classic/images/MozIcons/stock/menu/stock_media-fwd.png
skin/classic/images/MozIcons/stock/menu/gtk-goto-bottom.png
skin/classic/images/MozIcons/stock/menu/stock_list_bullet.png
skin/classic/images/MozIcons/stock/menu/format-justify-left.png
skin/classic/images/MozIcons/stock/menu/gtk-media-previous-ltr.png
skin/classic/images/MozIcons/stock/menu/mail-message-new.png
skin/classic/images/MozIcons/stock/menu/zoom-original.png
skin/classic/images/MozIcons/stock/menu/stock_zoom-1.png
skin/classic/images/MozIcons/stock/menu/gnome-logout.png
skin/classic/images/MozIcons/stock/menu/stock_bottom.png
skin/classic/images/MozIcons/stock/menu/gtk-italic.png
skin/classic/images/MozIcons/stock/menu/gtk-media-forward-rtl.png
skin/classic/images/MozIcons/stock/menu/stock_help.png
skin/classic/images/MozIcons/stock/menu/mail-send-receive.png
skin/classic/images/MozIcons/stock/menu/gtk-properties.png
skin/classic/images/MozIcons/stock/menu/gtk-paste.png
skin/classic/images/MozIcons/stock/menu/stock_text_underlined.png
skin/classic/images/MozIcons/stock/menu/gtk-strikethrough.png
skin/classic/images/MozIcons/stock/menu/mail_forward.png
skin/classic/images/MozIcons/stock/menu/zoom-out.png
skin/classic/images/MozIcons/stock/menu/remove.png
skin/classic/images/MozIcons/stock/menu/zoom-best-fit.png
skin/classic/images/MozIcons/stock/menu/object-rotate-left.png
skin/classic/images/MozIcons/stock/menu/stock_mail-reply.png
skin/classic/images/MozIcons/stock/menu/gtk-zoom-fit.png
skin/classic/images/MozIcons/stock/menu/gnome-session-logout.png
skin/classic/images/MozIcons/stock/menu/media-playback-stop.png
skin/classic/images/MozIcons/stock/menu/gohome.png
skin/classic/images/MozIcons/stock/menu/gtk-cancel.png
skin/classic/images/MozIcons/stock/menu/mail-reply-sender.png
skin/classic/images/MozIcons/stock/menu/viewmag1.png
skin/classic/images/MozIcons/stock/menu/stock_new-text.png
skin/classic/images/MozIcons/stock/menu/go-next.png
skin/classic/images/MozIcons/stock/menu/text_strike.png
skin/classic/images/MozIcons/stock/menu/player_end.png
skin/classic/images/MozIcons/stock/menu/stock_media-rew.png
skin/classic/images/MozIcons/stock/menu/gtk-zoom-out.png
skin/classic/images/MozIcons/stock/menu/bookmark_add.png
skin/classic/images/MozIcons/stock/menu/filesave.png
skin/classic/images/MozIcons/stock/menu/stock_new-appointment.png
skin/classic/images/MozIcons/stock/menu/view-refresh.png
skin/classic/images/MozIcons/stock/menu/format-indent-less.png
skin/classic/images/MozIcons/stock/menu/viewmag-.png
skin/classic/images/MozIcons/stock/menu/stock_list_enum.png
skin/classic/images/MozIcons/stock/menu/stock_first.png
skin/classic/images/MozIcons/stock/menu/object-flip-vertical.png
skin/classic/images/MozIcons/stock/menu/mail_replyall.png
skin/classic/images/MozIcons/stock/menu/stock_top.png
skin/classic/images/MozIcons/stock/menu/stock_mail-compose.png
skin/classic/images/MozIcons/stock/menu/insert-link.png
skin/classic/images/MozIcons/stock/menu/help-contents.png
skin/classic/images/MozIcons/stock/menu/gtk-delete.png
skin/classic/images/MozIcons/stock/menu/document-page-setup.png
skin/classic/images/MozIcons/stock/menu/edit-delete.png
skin/classic/images/MozIcons/stock/menu/document-properties.png
skin/classic/images/MozIcons/stock/menu/stock_text_italic.png
skin/classic/images/MozIcons/stock/menu/media-seek-forward.png
skin/classic/images/MozIcons/stock/menu/gnome-stock-mail-new.png
skin/classic/images/MozIcons/stock/menu/lock.png
skin/classic/images/MozIcons/stock/menu/filenew.png
skin/classic/images/MozIcons/stock/menu/gtk-media-previous-rtl.png
skin/classic/images/MozIcons/stock/menu/system-log-out.png
skin/classic/images/MozIcons/stock/menu/reload3.png
skin/classic/images/MozIcons/stock/menu/exit.png
skin/classic/images/MozIcons/stock/menu/stock_text_right.png
skin/classic/images/MozIcons/stock/menu/gtk-refresh.png
skin/classic/images/MozIcons/stock/menu/gtk-goto-last-ltr.png
skin/classic/images/MozIcons/stock/menu/stock_mail-forward.png
skin/classic/images/MozIcons/stock/menu/find.png
skin/classic/images/MozIcons/stock/menu/stop.png
skin/classic/images/MozIcons/stock/menu/stock_fullscreen.png
skin/classic/images/MozIcons/stock/menu/go-home.png
skin/classic/images/MozIcons/stock/menu/system-search.png
skin/classic/images/MozIcons/stock/menu/object-flip-horizontal.png
skin/classic/images/MozIcons/stock/menu/gtk-find-and-replace.png
skin/classic/images/MozIcons/stock/menu/gtk-print.png
skin/classic/images/MozIcons/stock/menu/stock_media-next.png
skin/classic/images/MozIcons/stock/menu/editclear.png
skin/classic/images/MozIcons/stock/menu/format-text-direction-rtl.png
skin/classic/images/MozIcons/stock/menu/gtk-add.png
skin/classic/images/MozIcons/stock/menu/gtk-stop.png
skin/classic/images/MozIcons/stock/menu/gtk-about.png
skin/classic/images/MozIcons/stock/menu/gtk-find.png
skin/classic/images/MozIcons/stock/menu/stock_mail-send-receive.png
skin/classic/images/MozIcons/stock/menu/stock_redo.png
skin/classic/images/MozIcons/stock/menu/stock_text_bold.png
skin/classic/images/MozIcons/stock/menu/stock_new-window.png
skin/classic/images/MozIcons/stock/menu/gtk-zoom-100.png
skin/classic/images/MozIcons/stock/menu/format-text-direction-ltr.png
skin/classic/images/MozIcons/stock/menu/bookmarks_list_add.png
skin/classic/images/MozIcons/stock/menu/gtk-quit.png
skin/classic/images/MozIcons/stock/menu/gtk-edit.png
skin/classic/images/MozIcons/stock/menu/list-add.png
skin/classic/images/MozIcons/stock/menu/document-send.png
skin/classic/images/MozIcons/stock/menu/mail-mark-junk.png
skin/classic/images/MozIcons/stock/menu/text_italic.png
skin/classic/images/MozIcons/stock/menu/format-text-underline.png
skin/classic/images/MozIcons/stock/menu/media-skip-backward.png
skin/classic/images/MozIcons/stock/menu/go-top.png
skin/classic/images/MozIcons/stock/menu/window-new.png
skin/classic/images/MozIcons/stock/menu/document-print-preview.png
skin/classic/images/MozIcons/stock/menu/player_stop.png
skin/classic/images/MozIcons/stock/menu/call-stop.png
skin/classic/images/MozIcons/stock/menu/window_nofullscreen.png
skin/classic/images/MozIcons/stock/menu/format-indent-more.png
skin/classic/images/MozIcons/stock/menu/stock_select-all.png
skin/classic/images/MozIcons/stock/menu/filefind.png
skin/classic/images/MozIcons/stock/menu/stock_paste.png
skin/classic/images/MozIcons/stock/menu/previous.png
skin/classic/images/MozIcons/stock/menu/stock_about.png
skin/classic/images/MozIcons/stock/menu/editdelete.png
skin/classic/images/MozIcons/stock/menu/player_rew.png
skin/classic/images/MozIcons/stock/menu/gnome-stock-mail-rpl.png
skin/classic/images/MozIcons/stock/menu/mail-mark-unread.png
skin/classic/images/MozIcons/stock/menu/stock_delete.png
skin/classic/images/MozIcons/stock/menu/stock_print.png
skin/classic/images/MozIcons/stock/menu/gtk-zoom-in.png
skin/classic/images/MozIcons/stock/menu/stock_last.png
skin/classic/images/MozIcons/stock/menu/stock_save.png
skin/classic/images/MozIcons/stock/menu/edit-clear.png
skin/classic/images/MozIcons/stock/menu/mail-mark-important.png
skin/classic/images/MozIcons/stock/menu/stock_new-tab.png
skin/classic/images/MozIcons/stock/menu/leftjust.png
skin/classic/images/MozIcons/stock/menu/bookmark-new.png
skin/classic/images/MozIcons/stock/menu/fileopen.png
skin/classic/images/MozIcons/stock/menu/gtk-clear.png
skin/classic/images/MozIcons/stock/menu/bottom.png
skin/classic/images/MozIcons/stock/menu/start.png
skin/classic/images/MozIcons/stock/menu/stock_mail-reply-to-all.png
skin/classic/images/MozIcons/stock/menu/stock_text_color_foreground.png
skin/classic/images/MozIcons/stock/menu/stock_media-prev.png
skin/classic/images/MozIcons/stock/menu/gtk-go-forward-ltr.png
skin/classic/images/MozIcons/stock/menu/gnome-run.png
skin/classic/images/MozIcons/stock/menu/stock_print-setup.png
skin/classic/images/MozIcons/stock/menu/gtk-go-back-ltr.png
skin/classic/images/MozIcons/stock/menu/mail-forward.png
skin/classic/images/MozIcons/stock/menu/stock_new-bcard.png
skin/classic/images/MozIcons/stock/menu/gtk-execute.png
skin/classic/images/MozIcons/stock/menu/stock_undo.png
skin/classic/images/MozIcons/stock/menu/gnome-stock-text-indent.png
skin/classic/images/MozIcons/stock/menu/reload.png
skin/classic/images/MozIcons/stock/menu/mail-send.png
skin/classic/images/MozIcons/stock/menu/redhat-home.png
skin/classic/images/MozIcons/stock/menu/view-fullscreen.png
skin/classic/images/MozIcons/stock/menu/document-save.png
skin/classic/images/MozIcons/stock/menu/media-playback-pause.png
skin/classic/images/MozIcons/stock/menu/tab_new.png
skin/classic/images/MozIcons/stock/menu/player_fwd.png
skin/classic/images/MozIcons/stock/menu/help-about.png
skin/classic/images/MozIcons/stock/menu/top.png
skin/classic/images/MozIcons/stock/menu/search.png
skin/classic/images/MozIcons/stock/menu/gtk-undo-ltr.png
skin/classic/images/MozIcons/stock/menu/gtk-media-rewind-rtl.png
skin/classic/images/MozIcons/stock/menu/go-bottom.png
skin/classic/images/MozIcons/stock/menu/redo.png
skin/classic/images/MozIcons/stock/menu/gnome-shutdown.png
skin/classic/images/MozIcons/stock/menu/call-start.png
skin/classic/images/MozIcons/stock/menu/gtk-go-down.png
skin/classic/images/MozIcons/stock/menu/stock_help-add-bookmark.png
skin/classic/images/MozIcons/stock/menu/stock_increase-font.png
skin/classic/images/MozIcons/stock/menu/gtk-unindent-rtl.png
skin/classic/images/MozIcons/stock/menu/stock_zoom-in.png
skin/classic/images/MozIcons/stock/menu/tools-check-spelling.png
skin/classic/images/MozIcons/stock/menu/gtk-copy.png
skin/classic/images/MozIcons/stock/menu/edit-copy.png
skin/classic/images/MozIcons/stock/menu/stock_cut.png
skin/classic/images/MozIcons/stock/menu/finish.png
skin/classic/images/MozIcons/stock/menu/gtk-go-back-rtl.png
skin/classic/images/MozIcons/stock/menu/gtk-media-play-ltr.png
skin/classic/images/MozIcons/stock/menu/gtk-open.png
skin/classic/images/MozIcons/stock/menu/gtk-underline.png
skin/classic/images/MozIcons/stock/menu/mail-reply-all.png
skin/classic/images/MozIcons/stock/menu/down.png
skin/classic/images/MozIcons/stock/menu/gtk-leave-fullscreen.png
skin/classic/images/MozIcons/stock/menu/text_under.png
skin/classic/images/MozIcons/stock/menu/gtk-close.png
skin/classic/images/MozIcons/stock/menu/insert-object.png
skin/classic/images/MozIcons/stock/menu/gtk-media-pause.png
skin/classic/images/MozIcons/stock/menu/gtk-jump-to-ltr.png
skin/classic/images/MozIcons/stock/menu/folder_new.png
skin/classic/images/MozIcons/stock/menu/stock_decrease-font.png
skin/classic/images/MozIcons/stock/menu/stock_zoom-out.png
skin/classic/images/MozIcons/stock/menu/stock_text_unindent.png
skin/classic/images/MozIcons/stock/menu/stock_search.png
skin/classic/images/MozIcons/stock/menu/view-restore.png
skin/classic/images/MozIcons/stock/menu/stock_up.png
skin/classic/images/MozIcons/stock/menu/fileprint.png
skin/classic/images/MozIcons/stock/menu/format-text-italic.png
skin/classic/images/MozIcons/stock/menu/gtk-goto-first-rtl.png
skin/classic/images/MozIcons/stock/menu/tab-new.png
skin/classic/images/MozIcons/stock/menu/stock_text_color_hilight.png
skin/classic/images/MozIcons/stock/menu/stock_mail-send.png
skin/classic/images/MozIcons/stock/menu/zoom-fit-best.png
skin/classic/images/MozIcons/stock/menu/go-last.png
skin/classic/images/MozIcons/stock/menu/stock_text_left.png
skin/classic/images/MozIcons/stock/menu/edit-find-replace.png
skin/classic/images/MozIcons/stock/menu/stock_properties.png
skin/classic/images/MozIcons/stock/menu/gtk-new.png
skin/classic/images/MozIcons/stock/menu/help-faq.png
skin/classic/images/MozIcons/stock/menu/gtk-revert-to-saved-ltr.png
skin/classic/images/MozIcons/stock/menu/xfce-system-lock.png
skin/classic/images/MozIcons/stock/menu/centrejust.png
skin/classic/images/MozIcons/stock/menu/up.png
skin/classic/images/MozIcons/stock/menu/gtk-justify-right.png
skin/classic/images/MozIcons/stock/menu/contact-new.png
skin/classic/images/MozIcons/stock/menu/stock_spellcheck.png
skin/classic/images/MozIcons/stock/shape_handles.png
skin/classic/images/MozIcons/stock/document-open.png
skin/classic/images/MozIcons/stock/previous-menu.png
skin/classic/images/MozIcons/stock/format_justify_fill.png
skin/classic/images/MozIcons/stock/format-text-underline-menu.png
skin/classic/images/MozIcons/stock/stock_3d_color_picker.png
skin/classic/images/MozIcons/stock/stock_list_bullet.png
skin/classic/images/MozIcons/stock/stock_standard_filter.png
skin/classic/images/MozIcons/stock/format_indent_less.png
skin/classic/images/MozIcons/stock/stock_snap_object.png
skin/classic/images/MozIcons/stock/make-same-horizontal-space.png
skin/classic/images/MozIcons/stock/stock_graphics_align_top.png
skin/classic/images/MozIcons/stock/edit_clear.png
skin/classic/images/MozIcons/stock/zoom-in-menu.png
skin/classic/images/MozIcons/stock/shape_move_front.png
skin/classic/images/MozIcons/stock/format_justify_right.png
skin/classic/images/MozIcons/stock/stock_list_enum.png
skin/classic/images/MozIcons/stock/document-new-menu.png
skin/classic/images/MozIcons/stock/stock_ungroup.png
skin/classic/images/MozIcons/stock/edit-delete.png
skin/classic/images/MozIcons/stock/shape_move_forwards.png
skin/classic/images/MozIcons/stock/document-save-menu.png
skin/classic/images/MozIcons/stock/make-same-vertical-space.png
skin/classic/images/MozIcons/stock/format_indent_more.png
skin/classic/images/MozIcons/stock/edit-copy-menu.png
skin/classic/images/MozIcons/stock/stock_bucketfill.png
skin/classic/images/MozIcons/stock/format-indent-more-menu.png
skin/classic/images/MozIcons/stock/stock_text_color_foreground-menu.png
skin/classic/images/MozIcons/stock/edit_redo.png
skin/classic/images/MozIcons/stock/stock_text_color_background.png
skin/classic/images/MozIcons/stock/stock_styles_fill_format_mode.png
skin/classic/images/MozIcons/stock/shape-group.png
skin/classic/images/MozIcons/stock/edit-paste-menu.png
skin/classic/images/MozIcons/stock/shape_move_back.png
skin/classic/images/MozIcons/stock/format_text_underline.png
skin/classic/images/MozIcons/stock/format-text-italic-menu.png
skin/classic/images/MozIcons/stock/stock_undo_history.png
skin/classic/images/MozIcons/stock/stock_format_numbering_bullets.png
skin/classic/images/MozIcons/stock/shape_move_backwards.png
skin/classic/images/MozIcons/stock/stock_text_color_foreground.png
skin/classic/images/MozIcons/stock/stock_hyperlink.png
skin/classic/images/MozIcons/stock/format_text_strikethrough.png
skin/classic/images/MozIcons/stock/stock_draw_text.png
skin/classic/images/MozIcons/stock/stock_increase_font.png
skin/classic/images/MozIcons/stock/document-save.png
skin/classic/images/MozIcons/stock/stock_mark.png
skin/classic/images/MozIcons/stock/format-text-bold-menu.png
skin/classic/images/MozIcons/stock/stock_text_double_click_to_edit.png
skin/classic/images/MozIcons/stock/stock_graphics_align_bottom.png
skin/classic/images/MozIcons/stock/stock_export.png
skin/classic/images/MozIcons/stock/stock_form_design_mode.png
skin/classic/images/MozIcons/stock/stock_graphics_align_left.png
skin/classic/images/MozIcons/stock/edit-undo-menu.png
skin/classic/images/MozIcons/stock/stock_snap_guides.png
skin/classic/images/MozIcons/stock/stock_decrease_font.png
skin/classic/images/MozIcons/stock/stock_text_select_text_only.png
skin/classic/images/MozIcons/stock/gtk-edit-menu.png
skin/classic/images/MozIcons/stock/insert_text.png
skin/classic/images/MozIcons/stock/stock_text_color_hilight.png
skin/classic/images/MozIcons/stock/edit_undo.png
skin/classic/images/MozIcons/stock/stock_new.png
skin/classic/images/pane-selector-bg-selected.png
skin/classic/images/hide-collection.gif
skin/classic/images/pencil-22.png
skin/classic/images/color-picker.png
skin/classic/images/pane-selector-advanced.png
skin/classic/images/pane-selector-export.png
skin/classic/images/align-center-bottom.png
skin/classic/images/pane-selector-openclipart.png
skin/classic/images/pane-selector-general.png
skin/classic/images/icon.svg
skin/classic/images/clipart.png
skin/classic/images/warning16.png
skin/classic/images/align-right-bottom.png
skin/classic/images/color-wheel-90.png
skin/classic/images/pencil.png
skin/classic/images/pan_on.png
skin/classic/images/align-right-top.png
skin/classic/images/pane-selector-macosx-bg-sel.png
skin/classic/images/pane-selector-bg-hover.png
skin/classic/images/bg-gray20.png
skin/classic/images/align-left-top.png
skin/classic/images/pane-selector-bg.png
skin/classic/images/48.png
skin/classic/images/pan.cur
skin/classic/images/color-wheel-70.png
skin/classic/richTextDialog.css
skin/classic/clipartBrowser.css
skin/classic/pencil-48.png
skin/classic/pencil.xpm
skin/classic/pageNoteDialog.css
skin/classic/pencil-24.png
skin/classic/miniToolbar.css
skin/classic/common.css
skin/classic/font.css
skin/classic/pencil-32.png
skin/classic/exportWizard.css
skin/classic/pencil.ico
skin/classic/stencilGenerator.css
skin/classic/htmlForeignObjectXUL.css
skin/classic/templateManagementDialog.css
skin/classic/win/images/align-bottom.png
skin/classic/win/images/align-right.png
skin/classic/win/images/align-left.png
skin/classic/win/images/align-middle.png
skin/classic/win/images/moblin/dalston-power-capplet.png
skin/classic/win/images/moblin/x-office-calendar.png
skin/classic/win/images/moblin/evince.png
skin/classic/win/images/moblin/stock_task-recurring.png
skin/classic/win/images/moblin/preferences-system-windows.png
skin/classic/win/images/moblin/image-x-generic.png
skin/classic/win/images/moblin/preferences-desktop-file-management.png
skin/classic/win/images/moblin/skype.png
skin/classic/win/images/moblin/preferences-mail-accounts.png
skin/classic/win/images/moblin/liferea.png
skin/classic/win/images/moblin/stock_contact-list.png
skin/classic/win/images/moblin/banshee.png
skin/classic/win/images/moblin/media-seek-backward.png
skin/classic/win/images/moblin/baobab.png
skin/classic/win/images/moblin/applets-screenshooter.png
skin/classic/win/images/moblin/system-shutdown.png
skin/classic/win/images/moblin/lastfm-audioscrobbler.png
skin/classic/win/images/moblin/gnome-planner.png
skin/classic/win/images/moblin/share.png
skin/classic/win/images/moblin/dialog-question.png
skin/classic/win/images/moblin/go-jump.png
skin/classic/win/images/moblin/format-justify-right.png
skin/classic/win/images/moblin/dates.png
skin/classic/win/images/moblin/tomboy.png
skin/classic/win/images/moblin/media-flash.png
skin/classic/win/images/moblin/weather-few-clouds-night.png
skin/classic/win/images/moblin/rawstudio.png
skin/classic/win/images/moblin/system-lock-screen.png
skin/classic/win/images/moblin/document-new.png
skin/classic/win/images/moblin/system-config-users.png
skin/classic/win/images/moblin/weather-showers.png
skin/classic/win/images/moblin/cheese-take-photo.png
skin/classic/win/images/moblin/document-save-as.png
skin/classic/win/images/moblin/mail-mark-notjunk.png
skin/classic/win/images/moblin/system-file-manager.png
skin/classic/win/images/moblin/emblem-favorite.png
skin/classic/win/images/moblin/gpk-install-catalog.png
skin/classic/win/images/moblin/weather-storm.png
skin/classic/win/images/moblin/send-email.png
skin/classic/win/images/moblin/system-software-install.png
skin/classic/win/images/moblin/computer-normal.png
skin/classic/win/images/moblin/format-text-strikethrough.png
skin/classic/win/images/moblin/gnome-mplayer.png
skin/classic/win/images/moblin/thunderbird.png
skin/classic/win/images/moblin/multimedia-player.png
skin/classic/win/images/moblin/trackpad-mouse.png
skin/classic/win/images/moblin/gnome-mines.png
skin/classic/win/images/moblin/format-text-bold.png
skin/classic/win/images/moblin/firefox.png
skin/classic/win/images/moblin/zoom-fit-page.png
skin/classic/win/images/moblin/object-rotate-right.png
skin/classic/win/images/moblin/align-bottom.png
skin/classic/win/images/moblin/process-stop.png
skin/classic/win/images/moblin/media-eject.png
skin/classic/win/images/moblin/query-free-busy.png
skin/classic/win/images/moblin/anjal.png
skin/classic/win/images/moblin/battery-good.png
skin/classic/win/images/moblin/go-first.png
skin/classic/win/images/moblin/frozen-bubble.png
skin/classic/win/images/moblin/media-player-banshee.png
skin/classic/win/images/moblin/appointment-new.png
skin/classic/win/images/moblin/marble.png
skin/classic/win/images/moblin/media-skip-forward.png
skin/classic/win/images/moblin/empathy.png
skin/classic/win/images/moblin/dialog-warning.png
skin/classic/win/images/moblin/preferences-other-hover.png
skin/classic/win/images/moblin/go-previous.png
skin/classic/win/images/moblin/edit-cut.png
skin/classic/win/images/moblin/browse-webcam-effects.png
skin/classic/win/images/moblin/x-office-address-book.png
skin/classic/win/images/moblin/edit-select-all.png
skin/classic/win/images/moblin/preferences-system.png
skin/classic/win/images/moblin/window-close-normal.png
skin/classic/win/images/moblin/text-html.png
skin/classic/win/images/moblin/session-properties.png
skin/classic/win/images/moblin/media-playlist-shuffle.png
skin/classic/win/images/moblin/user-trash.png
skin/classic/win/images/moblin/preferences-desktop-accessibility.png
skin/classic/win/images/moblin/lastfm-tag.png
skin/classic/win/images/moblin/view-calendar-day.png
skin/classic/win/images/moblin/window-close-hover.png
skin/classic/win/images/moblin/sync.png
skin/classic/win/images/moblin/wireless-signal-excellent.png
skin/classic/win/images/moblin/zoom-fit.png
skin/classic/win/images/moblin/document-recent.png
skin/classic/win/images/moblin/spinner-frame-3.png
skin/classic/win/images/moblin/accessories-calculator.png
skin/classic/win/images/moblin/edit-redo.png
skin/classic/win/images/moblin/gtk-dialog-error.png
skin/classic/win/images/moblin/media-record.png
skin/classic/win/images/moblin/gnome-aisleriot.png
skin/classic/win/images/moblin/user-info.png
skin/classic/win/images/moblin/document-print.png
skin/classic/win/images/moblin/toolbar-properties.png
skin/classic/win/images/moblin/palimpsest.png
skin/classic/win/images/moblin/media-playback-start.png
skin/classic/win/images/moblin/printer-default.png
skin/classic/win/images/moblin/media-optical.png
skin/classic/win/images/moblin/brush.png
skin/classic/win/images/moblin/ipod.png
skin/classic/win/images/moblin/gnome-sound-recorder.png
skin/classic/win/images/moblin/view-sort-descending.png
skin/classic/win/images/moblin/shape-text-color.png
skin/classic/win/images/moblin/dasher.png
skin/classic/win/images/moblin/view-sort-ascending.png
skin/classic/win/images/moblin/computer-hover.png
skin/classic/win/images/moblin/preferences-mail.png
skin/classic/win/images/moblin/dax.png
skin/classic/win/images/moblin/eog-image-collection.png
skin/classic/win/images/moblin/printer.png
skin/classic/win/images/moblin/gnome-power-manager.png
skin/classic/win/images/moblin/neverball.png
skin/classic/win/images/moblin/network-wired.png
skin/classic/win/images/moblin/podcast.png
skin/classic/win/images/moblin/go-down.png
skin/classic/win/images/moblin/gnome-settings-default-applications.png
skin/classic/win/images/moblin/garage.png
skin/classic/win/images/moblin/radio.png
skin/classic/win/images/moblin/gthumb.png
skin/classic/win/images/moblin/stock_appointment-reminder.png
skin/classic/win/images/moblin/document-open-recent.png
skin/classic/win/images/moblin/eog.png
skin/classic/win/images/moblin/abiword.png
skin/classic/win/images/moblin/gtk-ok.png
skin/classic/win/images/moblin/wireless-signal-good.png
skin/classic/win/images/moblin/go-up.png
skin/classic/win/images/moblin/window-close.png
skin/classic/win/images/moblin/phone-iphone.png
skin/classic/win/images/moblin/list-remove.png
skin/classic/win/images/moblin/format-justify-fill.png
skin/classic/win/images/moblin/insert-text.png
skin/classic/win/images/moblin/package-x-generic.png
skin/classic/win/images/moblin/fosfor.png
skin/classic/win/images/moblin/format-justify-center.png
skin/classic/win/images/moblin/battery-full.png
skin/classic/win/images/moblin/mplayer.png
skin/classic/win/images/moblin/console-xbox360.png
skin/classic/win/images/moblin/mail-sent.png
skin/classic/win/images/moblin/edit-find-hover.png
skin/classic/win/images/moblin/user-desktop.png
skin/classic/win/images/moblin/phone.png
skin/classic/win/images/moblin/printer-error.png
skin/classic/win/images/moblin/hornsey.png
skin/classic/win/images/moblin/audio-x-generic.png
skin/classic/win/images/moblin/control-center.png
skin/classic/win/images/moblin/medium-flash.png
skin/classic/win/images/moblin/web-services.png
skin/classic/win/images/moblin/object-crop.png
skin/classic/win/images/moblin/stock_lock.png
skin/classic/win/images/moblin/preferences-other.png
skin/classic/win/images/moblin/document-revert.png
skin/classic/win/images/moblin/view-refresh-hover.png
skin/classic/win/images/moblin/x-document-template.png
skin/classic/win/images/moblin/security.png
skin/classic/win/images/moblin/folder-new.png
skin/classic/win/images/moblin/gnome-tetravex.png
skin/classic/win/images/moblin/go-next-normal.png
skin/classic/win/images/moblin/format-justify-middle.png
skin/classic/win/images/moblin/desktop-effects.png
skin/classic/win/images/moblin/gnome-volume-control.png
skin/classic/win/images/moblin/add-folder-to-archive.png
skin/classic/win/images/moblin/insert-image.png
skin/classic/win/images/moblin/battery.png
skin/classic/win/images/moblin/edit-paste.png
skin/classic/win/images/moblin/source-playlist.png
skin/classic/win/images/moblin/gwibber.png
skin/classic/win/images/moblin/totem.png
skin/classic/win/images/moblin/simplescan.png
skin/classic/win/images/moblin/x-office-spreadsheet.png
skin/classic/win/images/moblin/virus-scanner.png
skin/classic/win/images/moblin/preferences-sound.png
skin/classic/win/images/moblin/stock_people.png
skin/classic/win/images/moblin/stock_meeting.png
skin/classic/win/images/moblin/folder-remote.png
skin/classic/win/images/moblin/edit-undo.png
skin/classic/win/images/moblin/align-right.png
skin/classic/win/images/moblin/bluetooth.png
skin/classic/win/images/moblin/stock_text-monospaced.png
skin/classic/win/images/moblin/ooo-writer.png
skin/classic/win/images/moblin/lastfm-neigbour.png
skin/classic/win/images/moblin/rhythmbox.png
skin/classic/win/images/moblin/drive-optical.png
skin/classic/win/images/moblin/app-installer.png
skin/classic/win/images/moblin/edit-find.png
skin/classic/win/images/moblin/retweet.png
skin/classic/win/images/moblin/wireless-signal-weak.png
skin/classic/win/images/moblin/view-calendar-list.png
skin/classic/win/images/moblin/camera-video.png
skin/classic/win/images/moblin/postr.png
skin/classic/win/images/moblin/preferences-myzone.png
skin/classic/win/images/moblin/zoom-in.png
skin/classic/win/images/moblin/gnometris.png
skin/classic/win/images/moblin/applications-multimedia.png
skin/classic/win/images/moblin/document-open.png
skin/classic/win/images/moblin/align-left.png
skin/classic/win/images/moblin/weather-clear.png
skin/classic/win/images/moblin/stock_list_bullet.png
skin/classic/win/images/moblin/preferences-composer.png
skin/classic/win/images/moblin/format-justify-left.png
skin/classic/win/images/moblin/process-stop-hover.png
skin/classic/win/images/moblin/drive-harddisk.png
skin/classic/win/images/moblin/vim.png
skin/classic/win/images/moblin/mail-message-new.png
skin/classic/win/images/moblin/spinner-frame-4.png
skin/classic/win/images/moblin/lastfm-personal.png
skin/classic/win/images/moblin/folder-drag-accept.png
skin/classic/win/images/moblin/shape-border-color.png
skin/classic/win/images/moblin/decrease-font.png
skin/classic/win/images/moblin/zoom-original.png
skin/classic/win/images/moblin/web-browser.png
skin/classic/win/images/moblin/gnome-iagno.png
skin/classic/win/images/moblin/system-users.png
skin/classic/win/images/moblin/mail-send-receive.png
skin/classic/win/images/moblin/make-same-horizontal-space.png
skin/classic/win/images/moblin/f-spot.png
skin/classic/win/images/moblin/go-up-normal.png
skin/classic/win/images/moblin/go-back-normal.png
skin/classic/win/images/moblin/text-x-generic-template.png
skin/classic/win/images/moblin/input-gaming.png
skin/classic/win/images/moblin/preferences-normal.png
skin/classic/win/images/moblin/format-justify-top.png
skin/classic/win/images/moblin/preferences-desktop-remote-desktop.png
skin/classic/win/images/moblin/zoom-out.png
skin/classic/win/images/moblin/object-rotate-left.png
skin/classic/win/images/moblin/preferences-desktop-locale.png
skin/classic/win/images/moblin/cheese-take-burst.png
skin/classic/win/images/moblin/align-middle.png
skin/classic/win/images/moblin/preferences-calendar-and-tasks.png
skin/classic/win/images/moblin/text-x-preview.png
skin/classic/win/images/moblin/media-playback-stop.png
skin/classic/win/images/moblin/weather-overcast.png
skin/classic/win/images/moblin/video-x-generic.png
skin/classic/win/images/moblin/x-office-presentation.png
skin/classic/win/images/moblin/printers.png
skin/classic/win/images/moblin/system-config-date.png
skin/classic/win/images/moblin/simple-scan.png
skin/classic/win/images/moblin/folder-visiting.png
skin/classic/win/images/moblin/mail-reply-sender.png
skin/classic/win/images/moblin/system-tray.png
skin/classic/win/images/moblin/songbird.png
skin/classic/win/images/moblin/go-next.png
skin/classic/win/images/moblin/slideshow-play.png
skin/classic/win/images/moblin/tv.png
skin/classic/win/images/moblin/preferences-other-normal.png
skin/classic/win/images/moblin/preferences-desktop.png
skin/classic/win/images/moblin/preferences-power-brightness.png
skin/classic/win/images/moblin/view-refresh.png
skin/classic/win/images/moblin/format-indent-less.png
skin/classic/win/images/moblin/stock_list_enum.png
skin/classic/win/images/moblin/object-flip-vertical.png
skin/classic/win/images/moblin/image-loading.png
skin/classic/win/images/moblin/preferences-system-tray.png
skin/classic/win/images/moblin/accessories-dictionary.png
skin/classic/win/images/moblin/insert-link.png
skin/classic/win/images/moblin/help-contents.png
skin/classic/win/images/moblin/edit-contact.png
skin/classic/win/images/moblin/edit-delete.png
skin/classic/win/images/moblin/document-properties.png
skin/classic/win/images/moblin/slideshow-start.png
skin/classic/win/images/moblin/gcompris.png
skin/classic/win/images/moblin/application-installer.png
skin/classic/win/images/moblin/pda.png
skin/classic/win/images/moblin/email.png
skin/classic/win/images/moblin/dialog-information.png
skin/classic/win/images/moblin/media-seek-forward.png
skin/classic/win/images/moblin/multimedia-player-apple-ipod.png
skin/classic/win/images/moblin/zoom-fit-width.png
skin/classic/win/images/moblin/tasks.png
skin/classic/win/images/moblin/user-home.png
skin/classic/win/images/moblin/dialog-error.png
skin/classic/win/images/moblin/make-same-vertical-space.png
skin/classic/win/images/moblin/kapman.png
skin/classic/win/images/moblin/go-home.png
skin/classic/win/images/moblin/system-search.png
skin/classic/win/images/moblin/go-up-hover.png
skin/classic/win/images/moblin/object-flip-horizontal.png
skin/classic/win/images/moblin/logo-icon.png
skin/classic/win/images/moblin/preferences-desktop-theme.png
skin/classic/win/images/moblin/preferences-autocompletion.png
skin/classic/win/images/moblin/media-playlist-repeat.png
skin/classic/win/images/moblin/spinner-frame-0.png
skin/classic/win/images/moblin/audio-volume-low.png
skin/classic/win/images/moblin/view-page-continuous.png
skin/classic/win/images/moblin/network-workgroup.png
skin/classic/win/images/moblin/stock_person.png
skin/classic/win/images/moblin/format-text-direction-rtl.png
skin/classic/win/images/moblin/xchat-gnome.png
skin/classic/win/images/moblin/inkscape.png
skin/classic/win/images/moblin/audacity.png
skin/classic/win/images/moblin/gnome-glines.png
skin/classic/win/images/moblin/utilities-terminal.png
skin/classic/win/images/moblin/ekiga.png
skin/classic/win/images/moblin/camera-photo.png
skin/classic/win/images/moblin/gimp.png
skin/classic/win/images/moblin/bisho.png
skin/classic/win/images/moblin/preferences-hover.png
skin/classic/win/images/moblin/stock_new-24h-appointment.png
skin/classic/win/images/moblin/power.png
skin/classic/win/images/moblin/gnome-search-tool.png
skin/classic/win/images/moblin/battery-low.png
skin/classic/win/images/moblin/x.png
skin/classic/win/images/moblin/scribus.png
skin/classic/win/images/moblin/edit-find--normal.png
skin/classic/win/images/moblin/align-top.png
skin/classic/win/images/moblin/format-text-direction-ltr.png
skin/classic/win/images/moblin/gnome-sudoku.png
skin/classic/win/images/moblin/gtk-edit.png
skin/classic/win/images/moblin/list-add.png
skin/classic/win/images/moblin/blender.png
skin/classic/win/images/moblin/window-switch.png
skin/classic/win/images/moblin/document-send.png
skin/classic/win/images/moblin/ooo-draw.png
skin/classic/win/images/moblin/text-x-script.png
skin/classic/win/images/moblin/mail-mark-junk.png
skin/classic/win/images/moblin/format-text-underline.png
skin/classic/win/images/moblin/audio-volume-high.png
skin/classic/win/images/moblin/media-skip-backward.png
skin/classic/win/images/moblin/x-office-drawing.png
skin/classic/win/images/moblin/view-page-facing.png
skin/classic/win/images/moblin/go-top.png
skin/classic/win/images/moblin/window-new.png
skin/classic/win/images/moblin/go-home-hover.png
skin/classic/win/images/moblin/call-stop.png
skin/classic/win/images/moblin/edit-preferences.png
skin/classic/win/images/moblin/format-indent-more.png
skin/classic/win/images/moblin/devhelp.png
skin/classic/win/images/moblin/export-document.png
skin/classic/win/images/moblin/gnome-gnect.png
skin/classic/win/images/moblin/WorldOfGooDemo.png
skin/classic/win/images/moblin/gtk-recordmydesktop.png
skin/classic/win/images/moblin/network-server.png
skin/classic/win/images/moblin/mail-attachment.png
skin/classic/win/images/moblin/gnome-network-properties.png
skin/classic/win/images/moblin/cheese.png
skin/classic/win/images/moblin/drive-removable-media.png
skin/classic/win/images/moblin/view-calendar-month.png
skin/classic/win/images/moblin/go-back-hover.png
skin/classic/win/images/moblin/gnome-display-properties.png
skin/classic/win/images/moblin/tuxpaint.png
skin/classic/win/images/moblin/preferences-system-network-proxy.png
skin/classic/win/images/moblin/anjuta.png
skin/classic/win/images/moblin/neverputt.png
skin/classic/win/images/moblin/text-x-generic.png
skin/classic/win/images/moblin/ghex.png
skin/classic/win/images/moblin/preferences-desktop-screensaver.png
skin/classic/win/images/moblin/format-justify-bottom.png
skin/classic/win/images/moblin/edit-clear.png
skin/classic/win/images/moblin/gconf-editor.png
skin/classic/win/images/moblin/audio-volume-medium.png
skin/classic/win/images/moblin/nautilus.png
skin/classic/win/images/moblin/system-software-update.png
skin/classic/win/images/moblin/pidgin.png
skin/classic/win/images/moblin/lastfm-recommended.png
skin/classic/win/images/moblin/phennec.png
skin/classic/win/images/moblin/preferences-certificates.png
skin/classic/win/images/moblin/call-hold.png
skin/classic/win/images/moblin/image-missing.png
skin/classic/win/images/moblin/empathy-accounts.png
skin/classic/win/images/moblin/audio-input-microphone.png
skin/classic/win/images/moblin/go-next-hover.png
skin/classic/win/images/moblin/gnome-klotski.png
skin/classic/win/images/moblin/mail-forward.png
skin/classic/win/images/moblin/user_auth.png
skin/classic/win/images/moblin/gallery.png
skin/classic/win/images/moblin/dialer.png
skin/classic/win/images/moblin/weather-snow.png
skin/classic/win/images/moblin/gnote.png
skin/classic/win/images/moblin/mail-send.png
skin/classic/win/images/moblin/gtk-apply.png
skin/classic/win/images/moblin/preferences-desktop-keyboard.png
skin/classic/win/images/moblin/view-fullscreen.png
skin/classic/win/images/moblin/go-today.png
skin/classic/win/images/moblin/document-save.png
skin/classic/win/images/moblin/gtk-index.png
skin/classic/win/images/moblin/media-playback-pause.png
skin/classic/win/images/moblin/dia.png
skin/classic/win/images/moblin/battery-caution.png
skin/classic/win/images/moblin/abrt.png
skin/classic/win/images/moblin/start-chat.png
skin/classic/win/images/moblin/gnome-mahjongg.png
skin/classic/win/images/moblin/extract-archive.png
skin/classic/win/images/moblin/source-smart-playlist.png
skin/classic/win/images/moblin/review-calendar-month.png
skin/classic/win/images/moblin/help-about.png
skin/classic/win/images/moblin/gnome-blackjack.png
skin/classic/win/images/moblin/stock_mail-filters-apply.png
skin/classic/win/images/moblin/shape-fill-color.png
skin/classic/win/images/moblin/view-refresh-normal.png
skin/classic/win/images/moblin/moblin-toolbar-properties.png
skin/classic/win/images/moblin/weather-severe-alert.png
skin/classic/win/images/moblin/go-bottom.png
skin/classic/win/images/moblin/console-ps3.png
skin/classic/win/images/moblin/computer.png
skin/classic/win/images/moblin/system-config-printer.png
skin/classic/win/images/moblin/gnome-control-center.png
skin/classic/win/images/moblin/call-start.png
skin/classic/win/images/moblin/headset.png
skin/classic/win/images/moblin/view-calendar-week.png
skin/classic/win/images/moblin/gnucash.png
skin/classic/win/images/moblin/system-tray-properties.png
skin/classic/win/images/moblin/input-mouse.png
skin/classic/win/images/moblin/evolution.png
skin/classic/win/images/moblin/add-files-to-archive.png
skin/classic/win/images/moblin/yelp.png
skin/classic/win/images/moblin/input-scanner.png
skin/classic/win/images/moblin/tweet-reply.png
skin/classic/win/images/moblin/3-way-call.png
skin/classic/win/images/moblin/moblin-web-browser.png
skin/classic/win/images/moblin/edit-copy.png
skin/classic/win/images/moblin/folder-open.png
skin/classic/win/images/moblin/gpk-prefs.png
skin/classic/win/images/moblin/contacts.png
skin/classic/win/images/moblin/preferences.png
skin/classic/win/images/moblin/font-x-generic.png
skin/classic/win/images/moblin/audio-volume-muted.png
skin/classic/win/images/moblin/mail-reply-all.png
skin/classic/win/images/moblin/gpk-repo.png
skin/classic/win/images/moblin/align-center.png
skin/classic/win/images/moblin/process-stop-normal.png
skin/classic/win/images/moblin/preferences-system-firewall.png
skin/classic/win/images/moblin/preferences-desktop-peripherals.png
skin/classic/win/images/moblin/accessories-text-editor.png
skin/classic/win/images/moblin/spinner-frame-2.png
skin/classic/win/images/moblin/application-x-executable.png
skin/classic/win/images/moblin/ooo-calc.png
skin/classic/win/images/moblin/network-wireless.png
skin/classic/win/images/moblin/increase-font.png
skin/classic/win/images/moblin/view-restore.png
skin/classic/win/images/moblin/format-text-italic.png
skin/classic/win/images/moblin/preferences-desktop-font.png
skin/classic/win/images/moblin/video-display.png
skin/classic/win/images/moblin/dalston.png
skin/classic/win/images/moblin/folder.png
skin/classic/win/images/moblin/zoom-fit-best.png
skin/classic/win/images/moblin/go-last.png
skin/classic/win/images/moblin/spinner-frame-1.png
skin/classic/win/images/moblin/weather-few-clouds.png
skin/classic/win/images/moblin/file-roller.png
skin/classic/win/images/moblin/edit-find-replace.png
skin/classic/win/images/moblin/view-calendar-workweek.png
skin/classic/win/images/moblin/help-faq.png
skin/classic/win/images/moblin/x-office-document.png
skin/classic/win/images/moblin/go-home-normal.png
skin/classic/win/images/moblin/x-office-document-template.png
skin/classic/win/images/moblin/preferences-desktop-keyboard-shortcuts.png
skin/classic/win/images/moblin/weather-clear-night.png
skin/classic/win/images/moblin/contact-new.png
skin/classic/win/images/moblin/glchess.png
skin/classic/win/images/align-top.png
skin/classic/win/images/MozIcons/stock/toolbar/stock_graphics-align-left.png
skin/classic/win/images/MozIcons/stock/toolbar/add.png
skin/classic/win/images/MozIcons/stock/toolbar/help.png
skin/classic/win/images/MozIcons/stock/toolbar/format-justify-right.png
skin/classic/win/images/MozIcons/stock/toolbar/stock_stroke_color.png
skin/classic/win/images/MozIcons/stock/toolbar/document-new.png
skin/classic/win/images/MozIcons/stock/toolbar/document-save-as.png
skin/classic/win/images/MozIcons/stock/toolbar/revert.png
skin/classic/win/images/MozIcons/stock/toolbar/stock_graphics-align-middle.png
skin/classic/win/images/MozIcons/stock/toolbar/format-text-strikethrough.png
skin/classic/win/images/MozIcons/stock/toolbar/format-text-bold.png
skin/classic/win/images/MozIcons/stock/toolbar/stock_to-bottom.png
skin/classic/win/images/MozIcons/stock/toolbar/object-rotate-right.png
skin/classic/win/images/MozIcons/stock/toolbar/gtk-fullscreen.png
skin/classic/win/images/MozIcons/stock/toolbar/stock_bring-backward.png
skin/classic/win/images/MozIcons/stock/toolbar/process-stop.png
skin/classic/win/images/MozIcons/stock/toolbar/document-export.png
skin/classic/win/images/MozIcons/stock/toolbar/edit-cut.png
skin/classic/win/images/MozIcons/stock/toolbar/edit-select-all.png
skin/classic/win/images/MozIcons/stock/toolbar/gtk-help.png
skin/classic/win/images/MozIcons/stock/toolbar/stock_object-behind.png
skin/classic/win/images/MozIcons/stock/toolbar/edit-redo.png
skin/classic/win/images/MozIcons/stock/toolbar/document-print.png
skin/classic/win/images/MozIcons/stock/toolbar/forward.png
skin/classic/win/images/MozIcons/stock/toolbar/back.png
skin/classic/win/images/MozIcons/stock/toolbar/document-open-recent.png
skin/classic/win/images/MozIcons/stock/toolbar/format-justify-fill.png
skin/classic/win/images/MozIcons/stock/toolbar/insert-text.png
skin/classic/win/images/MozIcons/stock/toolbar/undo.png
skin/classic/win/images/MozIcons/stock/toolbar/format-justify-center.png
skin/classic/win/images/MozIcons/stock/toolbar/document-revert.png
skin/classic/win/images/MozIcons/stock/toolbar/insert-image.png
skin/classic/win/images/MozIcons/stock/toolbar/edit-paste.png
skin/classic/win/images/MozIcons/stock/toolbar/edit-undo.png
skin/classic/win/images/MozIcons/stock/toolbar/next.png
skin/classic/win/images/MozIcons/stock/toolbar/edit-find.png
skin/classic/win/images/MozIcons/stock/toolbar/zoom-in.png
skin/classic/win/images/MozIcons/stock/toolbar/document-open.png
skin/classic/win/images/MozIcons/stock/toolbar/stock_list_bullet.png
skin/classic/win/images/MozIcons/stock/toolbar/format-justify-left.png
skin/classic/win/images/MozIcons/stock/toolbar/zoom-original.png
skin/classic/win/images/MozIcons/stock/toolbar/stock_to-top.png
skin/classic/win/images/MozIcons/stock/toolbar/make-same-horizontal-space.png
skin/classic/win/images/MozIcons/stock/toolbar/stock_graphics-align-bottom.png
skin/classic/win/images/MozIcons/stock/toolbar/stock_3d-color-picker.png
skin/classic/win/images/MozIcons/stock/toolbar/zoom-out.png
skin/classic/win/images/MozIcons/stock/toolbar/remove.png
skin/classic/win/images/MozIcons/stock/toolbar/zoom-best-fit.png
skin/classic/win/images/MozIcons/stock/toolbar/object-rotate-left.png
skin/classic/win/images/MozIcons/stock/toolbar/gtk-cancel.png
skin/classic/win/images/MozIcons/stock/toolbar/format-indent-less.png
skin/classic/win/images/MozIcons/stock/toolbar/stock_list_enum.png
skin/classic/win/images/MozIcons/stock/toolbar/object-flip-vertical.png
skin/classic/win/images/MozIcons/stock/toolbar/insert-link.png
skin/classic/win/images/MozIcons/stock/toolbar/help-contents.png
skin/classic/win/images/MozIcons/stock/toolbar/edit-delete.png
skin/classic/win/images/MozIcons/stock/toolbar/document-properties.png
skin/classic/win/images/MozIcons/stock/toolbar/exit.png
skin/classic/win/images/MozIcons/stock/toolbar/make-same-vertical-space.png
skin/classic/win/images/MozIcons/stock/toolbar/object-flip-horizontal.png
skin/classic/win/images/MozIcons/stock/toolbar/format-text-direction-rtl.png
skin/classic/win/images/MozIcons/stock/toolbar/gtk-about.png
skin/classic/win/images/MozIcons/stock/toolbar/stock_bucketfill.png
skin/classic/win/images/MozIcons/stock/toolbar/format-text-direction-ltr.png
skin/classic/win/images/MozIcons/stock/toolbar/gtk-edit.png
skin/classic/win/images/MozIcons/stock/toolbar/stock_object-infront.png
skin/classic/win/images/MozIcons/stock/toolbar/stock_text_color_background.png
skin/classic/win/images/MozIcons/stock/toolbar/format-text-underline.png
skin/classic/win/images/MozIcons/stock/toolbar/window-new.png
skin/classic/win/images/MozIcons/stock/toolbar/format-indent-more.png
skin/classic/win/images/MozIcons/stock/toolbar/stock_graphics-align-right.png
skin/classic/win/images/MozIcons/stock/toolbar/previous.png
skin/classic/win/images/MozIcons/stock/toolbar/stock_bring-forward.png
skin/classic/win/images/MozIcons/stock/toolbar/edit-clear.png
skin/classic/win/images/MozIcons/stock/toolbar/stock_graphics-align-center.png
skin/classic/win/images/MozIcons/stock/toolbar/stock_text_color_foreground.png
skin/classic/win/images/MozIcons/stock/toolbar/gnome-run.png
skin/classic/win/images/MozIcons/stock/toolbar/gtk-execute.png
skin/classic/win/images/MozIcons/stock/toolbar/redhat-home.png
skin/classic/win/images/MozIcons/stock/toolbar/document-save.png
skin/classic/win/images/MozIcons/stock/toolbar/help-about.png
skin/classic/win/images/MozIcons/stock/toolbar/stock_export.png
skin/classic/win/images/MozIcons/stock/toolbar/redo.png
skin/classic/win/images/MozIcons/stock/toolbar/edit-copy.png
skin/classic/win/images/MozIcons/stock/toolbar/gtk-close.png
skin/classic/win/images/MozIcons/stock/toolbar/insert-object.png
skin/classic/win/images/MozIcons/stock/toolbar/format-text-italic.png
skin/classic/win/images/MozIcons/stock/toolbar/stock_graphics-align-top.png
skin/classic/win/images/MozIcons/stock/toolbar/tab-new.png
skin/classic/win/images/MozIcons/stock/toolbar/stock_text_color_hilight.png
skin/classic/win/images/MozIcons/stock/toolbar/edit-find-replace.png
skin/classic/win/images/MozIcons/stock/toolbar/help-faq.png
skin/classic/win/images/MozIcons/stock/toolbar/centrejust.png
skin/classic/win/images/MozIcons/stock/menu/stock_graphics-align-left.png
skin/classic/win/images/MozIcons/stock/menu/help.png
skin/classic/win/images/MozIcons/stock/menu/format-justify-right.png
skin/classic/win/images/MozIcons/stock/menu/edit.png
skin/classic/win/images/MozIcons/stock/menu/document-new.png
skin/classic/win/images/MozIcons/stock/menu/document-save-as.png
skin/classic/win/images/MozIcons/stock/menu/format-text-strikethrough.png
skin/classic/win/images/MozIcons/stock/menu/format-text-bold.png
skin/classic/win/images/MozIcons/stock/menu/object-rotate-right.png
skin/classic/win/images/MozIcons/stock/menu/go-previous.png
skin/classic/win/images/MozIcons/stock/menu/edit-cut.png
skin/classic/win/images/MozIcons/stock/menu/edit-select-all.png
skin/classic/win/images/MozIcons/stock/menu/preferences-system.png
skin/classic/win/images/MozIcons/stock/menu/edit-redo.png
skin/classic/win/images/MozIcons/stock/menu/document-print.png
skin/classic/win/images/MozIcons/stock/menu/application-exit.png
skin/classic/win/images/MozIcons/stock/menu/list-remove.png
skin/classic/win/images/MozIcons/stock/menu/format-justify-fill.png
skin/classic/win/images/MozIcons/stock/menu/insert-text.png
skin/classic/win/images/MozIcons/stock/menu/format-justify-center.png
skin/classic/win/images/MozIcons/stock/menu/stock_lock.png
skin/classic/win/images/MozIcons/stock/menu/insert-image.png
skin/classic/win/images/MozIcons/stock/menu/edit-paste.png
skin/classic/win/images/MozIcons/stock/menu/edit-undo.png
skin/classic/win/images/MozIcons/stock/menu/edit-find.png
skin/classic/win/images/MozIcons/stock/menu/document-open.png
skin/classic/win/images/MozIcons/stock/menu/stock_list_bullet.png
skin/classic/win/images/MozIcons/stock/menu/format-justify-left.png
skin/classic/win/images/MozIcons/stock/menu/stock_graphics-align-bottom.png
skin/classic/win/images/MozIcons/stock/menu/stock_3d-color-picker.png
skin/classic/win/images/MozIcons/stock/menu/object-rotate-left.png
skin/classic/win/images/MozIcons/stock/menu/go-next.png
skin/classic/win/images/MozIcons/stock/menu/stock_graphics-align-centered.png
skin/classic/win/images/MozIcons/stock/menu/format-indent-less.png
skin/classic/win/images/MozIcons/stock/menu/stock_list_enum.png
skin/classic/win/images/MozIcons/stock/menu/object-flip-vertical.png
skin/classic/win/images/MozIcons/stock/menu/insert-link.png
skin/classic/win/images/MozIcons/stock/menu/stock_ungroup.png
skin/classic/win/images/MozIcons/stock/menu/edit-delete.png
skin/classic/win/images/MozIcons/stock/menu/document-properties.png
skin/classic/win/images/MozIcons/stock/menu/goto.png
skin/classic/win/images/MozIcons/stock/menu/object-flip-horizontal.png
skin/classic/win/images/MozIcons/stock/menu/list-add.png
skin/classic/win/images/MozIcons/stock/menu/format-text-underline.png
skin/classic/win/images/MozIcons/stock/menu/window-new.png
skin/classic/win/images/MozIcons/stock/menu/format-indent-more.png
skin/classic/win/images/MozIcons/stock/menu/stock_graphics-align-right.png
skin/classic/win/images/MozIcons/stock/menu/edit-clear.png
skin/classic/win/images/MozIcons/stock/menu/stock_graphics-align-center.png
skin/classic/win/images/MozIcons/stock/menu/stock_text_color_foreground.png
skin/classic/win/images/MozIcons/stock/menu/properties.png
skin/classic/win/images/MozIcons/stock/menu/document-save.png
skin/classic/win/images/MozIcons/stock/menu/help-about.png
skin/classic/win/images/MozIcons/stock/menu/stock_export.png
skin/classic/win/images/MozIcons/stock/menu/redo.png
skin/classic/win/images/MozIcons/stock/menu/stock_increase-font.png
skin/classic/win/images/MozIcons/stock/menu/edit-copy.png
skin/classic/win/images/MozIcons/stock/menu/stock_group.png
skin/classic/win/images/MozIcons/stock/menu/insert-object.png
skin/classic/win/images/MozIcons/stock/menu/stock_decrease-font.png
skin/classic/win/images/MozIcons/stock/menu/format-text-italic.png
skin/classic/win/images/MozIcons/stock/menu/stock_graphics-align-top.png
skin/classic/win/images/MozIcons/stock/menu/tab-new.png
skin/classic/win/images/MozIcons/stock/menu/stock_text_color_hilight.png
skin/classic/win/images/MozIcons/stock/menu/edit-find-replace.png
skin/classic/win/images/MozIcons/stock/menu/help-faq.png
skin/classic/win/images/MozIcons/stock/menu/stock_lock-open.png
skin/classic/win/images/align-center.png
skin/classic/win/icons.css
skin/classic/win/platform.css
skin/classic/pencil-42.png
skin/classic/pCanvas.css
skin/classic/icon.svg
skin/classic/mac/platform.css
skin/classic/pencil.png
skin/classic/pencil-16.png
skin/classic/htmlForeignObject.css
skin/classic/pencil-64.png
skin/classic/pencil.css
skin/classic/dialog.css
main-window.icns
chrome.manifest
locale/vi/pencil.dtd
locale/vi/pencil.properties
locale/en-US/pencil.dtd
locale/en-US/pencil.properties
application.ini
license.txt
defaults/preferences/debug.js
defaults/preferences/pencil.js
)
